---
abstract: 'concat some static files to one resource'
author:
  - cho45
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-StaticShared
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0
  DateTime::Format::HTTP: 0
  Digest::SHA1: 0
  Filter::Util::Call: 0
  Path::Class: 0
  Plack: 0
  Plack::Request: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/Plack-Middleware-StaticShared.git
version: 0.02
